typedef struct int_ll* int_ll_ptr;
typedef struct int_ll int_ll;
void int_ll_insert(int_ll_ptr root, R_xlen_t key, int value);
int_ll_ptr int_ll_next(int_ll_ptr root);
R_xlen_t int_ll_key(int_ll_ptr root);
int int_ll_value(int_ll_ptr root);
int_ll_ptr int_ll_instantiate(R_xlen_t key, int value);
void int_ll_free(int_ll_ptr root);
R_xlen_t int_ll_size(int_ll_ptr root);
void int_ll_set_value(int_ll_ptr root, int value);